action_set_relative(1)
action_kill_object()
with (red_2_)
    action_change_object(33, 0)
action_set_score(180)
with (very_final_boss_s_flame_)
    action_change_object(80, 0)
action_set_score(1000)
action_set_relative(0)
