action_set_relative(1)
action_kill_object()
with (guard_ghosts_)
    action_kill_object()
with (hp_1_)
    action_change_object(33, 0)
with (still_ghost_)
    action_kill_object()
with (green_1_)
    action_change_object(33, 0)
with (ghost_guard_1_)
    action_kill_object()
action_set_score(30)
action_set_relative(0)
