action_set_relative(1)
action_kill_object()
with (yellow_3_)
    action_change_object(46, 0)
with (yellow_4_)
    action_change_object(47, 0)
with (red_1_)
    action_change_object(33, 0)
with (ghost_guard_5_)
    action_kill_object()
action_set_score(150)
action_set_relative(0)
