action_set_relative(1)
action_kill_object()
with (hp_2_)
    action_change_object(33, 0)
with (hp_3_)
    action_change_object(42, 0)
with (green_3_)
    action_change_object(42, 0)
with (green_4_)
    action_change_object(43, 0)
with (green_5_)
    action_change_object(44, 0)
with (green_6_)
    action_change_object(45, 0)
with (green_2_)
    action_change_object(33, 0)
with (ghost_guard_2_)
    action_kill_object()
action_set_score(60)
action_set_relative(0)
