action_set_relative(1)
action_kill_object()
with (hp_3_)
    action_change_object(33, 0)
with (boss_1_)
    action_kill_object()
with (object37)
    action_kill_object()
with (phantom_ghost_)
    action_kill_object()
with (still_ghost_)
    action_kill_object()
with (dragorn)
    action_kill_object()
with (possessed_best_friend_)
    action_change_object(53, 0)
with (final_boss_)
    action_kill_object()
with (yellow_1_)
    action_change_object(33, 0)
with (ghost_guard_3_)
    action_kill_object()
action_set_score(90)
action_set_relative(0)
